language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: gcs
  edge: true
  access_key_id:
    secure: "oJfcY62IGO7KKIX+/muWwquclGSBuRI86UHWRp9ke/SJkJ//dWYhomJ7QPVwzU/8mX+N5IsFK00GLXfOAHGeXsxHwGxEdTLq8KOjV6rxH2rnqnz2UYJaRyyYdFRFvLIq44aXZifDpEb8SM/Cw/HzFokzbO/7QKugkeU7BNJEGb3BETbxh66GYAFPzX4k7C+x6pb7HksnykLjBFFN/ON7x4ovsi2N+Fd0h58NeudlylXKPDaSUhb6bx7pQ2CY8nds6CO9uwRI6P0E8zpd7hWz6/XL9cH3aCgxO+ICmLgQqMIjg9b7i4E8CJhYzkaCJH7dkRX1/M8LzZnxI0UkIpqkRCZyAakMCZdT2eBgtn4osG59/05A1D2CqTgNv4LMVEDFv8ALmBBNaUQ4S2dcD3zvXvtU8Maf1xVQUQnW3tf1VVBh0GWXaBjdZLExx8Nd6HJKYsZhpVHcnyvGtJmU2kemetSq08MNXSrNtjaEBf6uMqXGE0AHb/sGz6W01bf/EkkIkatzvCVeV5NhR4P8GWQnOuzGfchzvz0ZS08nHUtGtS5lyYmPUg0IH7+7CokbbBIpYEDivzdBPxT0MSpauoZOI3r1eJxCiBL84q8SLYVrDeJOegpD6+MHnqgqi7QsAD353Sb76fgV9He08ofBXiCZejNsxMu4PA7IAXX9Q/pNvWM="
  secret_access_key:
    secure: "jtefkaHDWb+QTgGTsaSRAL9gIPVcrgxzIgPHNIiPDH8WW2DyBpE2Tx2FWKChvi6fkDeWI/Y0Ci0kLdmcphvy1BVysl6PGsTZtRADFIXoq2LnmAKTgO98y4PtGRak23LpsA3MgvCDnn4Ae0JGMnIXRTatjtkHggOG/oVq42Cz4ZQAndQJWuf+IQszLO3i9KksrYhfzpTRv8fR9oEr2h8NzdMY99iRWu0m2tRoOK+NGVHgCtQizFe4Sp2QCYmRhd/0YYg01Y9NyMquYr3jRNrnPwh42anoxpimIX1Inn4K5azZt6Zog7xjcKs8i4SYeRriXFlzE5WLeOnNIhnciswqE67EGBEYTdrw7rn5ys/IAGK/+kMBzFf2SauhkMdU491zSOA5GRfis31YgjK4Gz3+IQhluaJSEdL9TQRgWSuWz3tLKoVU0j3fnh5TTlE7Qz7nmiyTygoTxbcrzPOr5nVuwTWhmceAXLAeLrSH3OL6ZBs68tJZutUqPVDxTIoXMAcdOkH97k7ppz3llmnVnJfQSPFRawpsORbOClgzAw+W2YUoZmVUyHb+ctsTLUNH0Xicbzzb+vAtiLE4y5Xjo/lYQvQzJ/ez/MDsT6BPzJ/GtEjgI9Ki0udeKKyK327spijdgZrnRHwPVKegUMPdEZw/iqtEBWxFBaQz/DRvWrcbfqg="
  bucket: beta.mmacc.uk
  local_dir: dist
  skip_cleanup: true
  acl: "public-read"
  detect_encoding: true
  cache_control: "public, max-age=31536000"
  on:
    branch: master
    repo: mmaccuk/mmacc.uk
